### ISSUE TITLE
 [Rollup] RollupError: Expression expected

### ISSUE THREAD

**Issue by jeanbenoit-richez** [torusresearch/torus-cli#57]
Hi,
I'm using `torus-cli` to build my react typescript component librairie.
I'm getting an error when i'm trying to build it with `build` command:
```
 X Expression expected (Note that you need plugins to import files that are not JavaScript)
◼ bundle.cjs.js
◼ bundle.umd.min.js
Expression expected (Note that you need plugins to import files that are not JavaScript)
RollupError: Expression expected
```

I have a a single entry point like this:
```
import * from './test1'
import * from './test2'
import * from './test3'
```

Before I was using rollup alone, and i got some errors like that fixed by adding plugins to bundle file with unsupported extensions (.json,.css).
But in this case the error is not telling that much...

**Comment by chaitanyapotti** [comment]
This package doesn't build ts syntax by default.
you need to add a babel plugin @babel/preset-typescript in babel.config.js file to make it work.

**Comment by jeanbenoit-richez** [comment]
Hi,
Yes that’s what I saw after looking into the source code.
But it should be as the npm REAME says that this library is made for
building Typescript ready library.
For people that build react library, you also need to add
@babel/react-babel preset before typescript preset.
